### PR TITLE
Return neutral code when nothing to commit

### PR DESCRIPTION
**Pull request by leny**
Here's an implementation for the issue addressed in issue #7 

The process return a `neutral` when there's nothing to commit, instead of an error.

### CODE REVIEW

**Comment by leny** [comment]
(sorry for the revert, I erronously included the commit from PR #8 - the revert is to fix that)

**Comment by maxheld83** [comment]
Uh I'm a little confused about this, so correct me if I have this all wrong @leny.

I see two *separate* issues here:

**1. The current action appears to error out when there is nothing to commit. **

This does not, on the face of it, make much sense.
I can think of any number of scenarios where, for some commits to the source *do not cause* a diff in the build asset `dir/`.
Erroring it clearly isn't the right response here, because there's nothing wrong per se.
I also tend to think that `78` status might not be quite right, because as per the GitHub actions spec:

> When an action returns this exit status, GitHub terminates all concurrently running actions and prevents any future actions from starting.

This, again, in some scenarios isn't what users might want or expect.

Also, I *think* this problem should only occur in the first place for deploys from `.` where there already (qua github actions provisioning of the workspace) *is* a git repo. In any `subdir/`, there won't be a git repo, and so there'd by definition always be something to commit.
Thus just as an aside.

**2. If deploying from `.`, this might cause an "infinite loop" of sorts (if 1 were fixed).**.
That's also bad.
I wonder though, whether the correct response to this wouldn't be to:

1) Commit sources to one branch, and deploy from some other branch (`gh-pages`).
2) Simply add a [filter action](https://github.com/actions/bin/tree/master/filter) before the deploy, and have the workflow continue only for !`gh-pages` or even just `master`, or whatever the plan may be.

**Comment by maxheld83** [comment]
Sorry this got more complicated than expected.

So my (preliminary) suggestion would be to **just `exit 0` instead of `exit 78` for empty commits and rely on filter actions to avoid infinite loops.**

@leny Does that make sense? Does that meet user expectations and keep things simple to reason about?

Set me straight if I got this wrong.

**Comment by leny** [comment]
The more I think of it, the more I think the `exit 0` is what makes more sense, and the other cases should be addressed with a **filter** action, as you suggest.

**Comment by maxheld83** [comment]
perfect, will merge, test and ship this then.
Thanks for the quick turnaround and great contributions @leny!

**Pull request merged**
